In [1]:
import pandas as pd

emissions = pd.read_csv("https://koumoul.com/s/data-fair/api/v1/datasets/igt-pouvoir-de-rechauffement-global/convert")
emissions.head(2)

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207

In [2]:
emissions_copy = emissions[['INSEE commune', 'Commune', 'Autres transports international', 'Autres transports']].copy()
emissions_copy.head()

,INSEE commune,Commune,Autres transports international,Autres transports
0,01001,L'ABERGEMENT-CLEMENCIAT,NaN,NaN
1,01002,L'ABERGEMENT-DE-VAREY,NaN,NaN
2,01004,AMBERIEU-EN-BUGEY,NaN,212.577908
3,01005,AMBERIEUX-EN-DOMBES,NaN,NaN
4,01006,AMBLEON,NaN,NaN

In [7]:
emissions_copy = emissions_copy.rename({"INSEE commune": "code_insee", "Autres transports": "transports", "Autres transports international": "transports_international"}, axis=1)
emissions_copy.head()

  code_insee                  Commune  transports_international  transports
0      01001  L'ABERGEMENT-CLEMENCIAT                       NaN         NaN
1      01002    L'ABERGEMENT-DE-VAREY                       NaN         NaN
2      01004        AMBERIEU-EN-BUGEY                       NaN  212.577908
3      01005      AMBERIEUX-EN-DOMBES                       NaN         NaN
4      01006                  AMBLEON                       NaN         NaN

## Question 3

In [13]:
emissions_copy.fillna(0, inplace=True)
emissions_copy["transports"]=emissions_copy["transports"].astype(int)
emissions_copy.head()

  code_insee                  Commune  transports_international  transports
0      01001  L'ABERGEMENT-CLEMENCIAT                       0.0           0
1      01002    L'ABERGEMENT-DE-VAREY                       0.0           0
2      01004        AMBERIEU-EN-BUGEY                       0.0         212
3      01005      AMBERIEUX-EN-DOMBES                       0.0           0
4      01006                  AMBLEON                       0.0           0

In [19]:
emissions["dep"] = emissions["INSEE commune"].astype(str).str[:2]
emissions.head()

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire,dep
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,NaN,NaN,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172,01
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,NaN,NaN,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207,01
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,NaN,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934,01
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,NaN,NaN,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357,01
4,01006,AMBLEON,448.966808,NaN,NaN,77.033834,48.401549,NaN,NaN,43.714019,398.786800,51.681756,01

In [ ]:
emissions.fillna(0, inplace=True) #pour virer les N/A dans émissions et pour éviter d'avoir ça dans les colonnes

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire,dep,transports_total
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,0.000000,0.0,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172,01,0.0
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,0.000000,0.0,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207,01,0.0
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,0.0,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934,01,0.0
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,0.000000,0.0,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357,01,0.0
4,01006,AMBLEON,448.966808,0.000000,0.0,77.033834,48.401549,0.000000,0.000000,43.714019,398.786800,51.681756,01,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35793,95676,VILLERS-EN-ARTHIES,1628.065094,0.000000,0.0,165.045396,65.063617,11.772789,34.556067,176.098160,309.627908,235.439109,95,0.0
35794,95678,VILLIERS-ADAM,698.630772,0.000000,0.0,1331.126598,111.480954,2.354558,6.911213,1395.529811,18759.370071,403.404815,95,0.0
35795,95680,VILLIERS-LE-BEL,107.564967,0.000000,0.0,8367.174532,225.622903,534.484607,1568.845431,22613.830247,12217.122402,13849.512001,95,0.0
35796,95682,VILLIERS-LE-SEC,1090.890170,0.000000,0.0,326.748418,108.969749,2.354558,6.911213,67.235487,4663.232127,85.657725,95,0.0
35797,95690,WY-DIT-JOLI-VILLAGE,1495.103542,0.000000,0.0,125.236417,97.728612,4.709115,13.822427,117.450851,504.400972,147.867245,95,0.0

In [32]:
col_emissions=["Agriculture","Autres transports","Autres transports international","CO2 biomasse hors-total","Déchets","Energie","Industrie hors-énergie","Résidentiel","Routier"]
emissions["transports_total"] = emissions[col_emissions].sum(axis=1) #axis = 1 pour sommer sur les colonnes
emissions.head()

,INSEE commune,Commune,Agriculture,Autres transports,Autres transports international,CO2 biomasse hors-total,Déchets,Energie,Industrie hors-énergie,Résidentiel,Routier,Tertiaire,dep,transports_total
0,01001,L'ABERGEMENT-CLEMENCIAT,3711.425991,0.000000,0.0,432.751835,101.430476,2.354558,6.911213,309.358195,793.156501,367.036172,01,5357.388769
1,01002,L'ABERGEMENT-DE-VAREY,475.330205,0.000000,0.0,140.741660,140.675439,2.354558,6.911213,104.866444,348.997893,112.934207,01,1219.877412
2,01004,AMBERIEU-EN-BUGEY,499.043526,212.577908,0.0,10313.446515,5314.314445,998.332482,2930.354461,16616.822534,15642.420313,10732.376934,01,52527.312185
3,01005,AMBERIEUX-EN-DOMBES,1859.160954,0.000000,0.0,1144.429311,216.217508,94.182310,276.448534,663.683146,1756.341319,782.404357,01,6010.463082
4,01006,AMBLEON,448.966808,0.000000,0.0,77.033834,48.401549,0.000000,0.000000,43.714019,398.786800,51.681756,01,1016.903011

In [ ]:
emissions_copy